version: '3.8'

services:
  backend:
    build:
      context: ./job-portal-server-side
      dockerfile: Dockerfile.backend
    container_name: job_portal_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Use the container names for inter-service communication
      - URL_SERVER_PYTHON=http://ai_http_server:9090
      - SOCKET_SERVER_PYTHON=tcp://python_server:5555
      - DATABASE_URL=mysql://root:root@db:3306/digitefa_job_portal
    env_file:
      - ./job-portal-server-side/.env.development
    volumes:
      - ./job-portal-server-side/public:/usr/src/app/public
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: job_portal_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=digitefa_job_portal
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - app_network

  python_server:
    build:
      context: ./job-portal-server-side/python
      dockerfile: Dockerfile.python
    container_name: job_portal_python_server
    restart: unless-stopped
    ports:
      - "5555:5555"
    networks:
      - app_network

  ai_http_server:
    build:
      context: ./digitefa-python
      dockerfile: Dockerfile
    container_name: job_portal_ai_http_server
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - app_network

  frontend_client:
    build:
      context: ./job-portal-client-side
      dockerfile: Dockerfile
    container_name: job_portal_client
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app_network

  frontend_cms:
    build:
      context: ./job-portal-clientside-cms
      dockerfile: dockerfile
    container_name: job_portal_cms
    restart: unless-stopped
    ports:
      - "5173:5173"
    networks:
      - app_network

  lms_be_app:
    build:
      context: ./lms-server-side
      dockerfile: Dockerfile
    image: server-side
    container_name: lms-be-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./lms-server-side:/var/www
    networks:
      - app_network

  lms_be_nginx:
    image: nginx:alpine
    container_name: lms-be-nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./lms-server-side:/var/www
      - ./lms-server-side/nginx:/etc/nginx/conf.d/
    networks:
      - app_network

  lms_fe_app:
    build:
      context: ./lms-client-side
      dockerfile: Dockerfile
    image: client-side
    container_name: lms-fe-container
    restart: unless-stopped
    ports:
      - "8800:80"
    environment:
      - VUE_APP_API_URL=http://localhost:8888/api
      - VUE_APP_STUDENT_PROFILE_URL=http://localhost:8888/uploads/Student/Student Profile
      - VUE_APP_TEACHER_PROFILE_URL=http://localhost:8888/uploads/Teacher/Profile Picture
      - VUE_APP_COURSE_THUMBNAIL_URL=http://localhost:8888/uploads/Courses/Thumbnail
      - VUE_APP_TEACHER_ABOUT_URL=http://localhost:8888/uploads
      - VUE_APP_TEACHER_MEDIA_PARTNER_URL=http://localhost:8888/uploads/media_partner
    working_dir: /app
    volumes:
      - ./lms-client-side:/app
    networks:
      - app_network

  lms_fe_nginx:
    image: nginx:alpine
    container_name: lms-fe-nginx
    restart: unless-stopped
    ports:
      - "3300:80"
    volumes:
      - ./lms-client-side/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

  lms_cms_app:
    build:
      context: ./lms-cms
      dockerfile: Dockerfile
    image: cms
    container_name: lms-cms-container
    restart: unless-stopped
    ports:
      - "8880:80"
    environment:
      - VUE_APP_API_URL=http://localhost:8888/api
      - VUE_APP_TEACHER_IDENTITY_URL=http://localhost:8888/uploads/Teacher/Identity
      - VUE_APP_TEACHER_PORTOFOLIO_URL=http://localhost:8888/uploads/Teacher/Portofolio
      - VUE_APP_TEACHER_PROFILE_URL=http://localhost:8888/uploads/Teacher/Profile Picture
      - VUE_APP_TEACHER_CERTIFICATE_URL=http://localhost:8888/uploads/Teacher/Teacher Certificates
      - VUE_APP_COURSE_THUMBNAIL_URL=http://localhost:8888/uploads/Courses/Thumbnail
    working_dir: /app
    volumes:
      - ./lms-cms:/app
    networks:
      - app_network

  lms_cms_nginx:
    image: nginx:alpine
    container_name: lms-cms-nginx
    restart: unless-stopped
    ports:
      - "3330:80"
    volumes:
      - ./lms-cms/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:
    name: digitefa_app_network

volumes:
  db_data:


